apiVersion: v1
kind: Service
metadata:
  name: codecraft-api
  labels:
    app: codecraft-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: codecraft-api 